[package]
name = "names-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
names-core.workspace = true
names-resolve.workspace = true
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "net", "macros", "fs", "signal", "io-util"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
