[package]
name = "pubdom-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "fips-pubdomd"
path = "src/main.rs"

[dependencies]
pubdom-core.workspace = true
pubdom-resolve.workspace = true
nostr-sdk = { version = "0.44", default-features = false }
simple-dns = "0.11"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
notify = "8"
notify-debouncer-mini = "0.7"
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "net", "macros", "fs", "signal", "io-util"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
